package:
  name: py_tsyganenko
  version: 0.1.3
source:
  git_rev: main
  git_url: https://github.com/LaboratoryOfPlasmaPhysics/py_tsyganenko
requirements:
  build:
    - python {{ python }}
    - numpy
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}
    - meson
    - ninja
    - git
    - pybind11
about:
  home: https://github.com/LaboratoryOfPlasmaPhysics/py_tsyganenko
  license: GPLv3
  license_file: COPYING

